### ISSUE TITLE
Make Option<Pointer> zero overhead

### ISSUE THREAD

**Issue by kvark** [kvark/froggy#10]
Rust nightly supports marking the structs as non-zeroable: https://doc.rust-lang.org/core/nonzero/struct.NonZero.html

This would ensure that storing `Option<Pointer<T>>` is not heavier than just `Pointer<T>`

**Comment by DaseinPhaos** [comment]
I noticed that `Pointer<T>` has two `Arc` fileds. 
As `Arc`s wrap around `Shared` which in turn wraps `NonZero`, doesn't that already suffice to guarantee that `Option<Pointer>` is zero overhead?

Teseting on my machine confirms that

```
assert_eq!(
    std::mem::size_of::<Option<Pointer<T>>>(),
    std::mem::size_of::<Pointer<T>>()
);
```

**Comment by kvark** [comment]
wow, that's very sweet, thanks for investigation!
