### ISSUE TITLE
Use sync primitives from parking_lot library

### ISSUE THREAD

**Issue by vitvakatu** [kvark/froggy#23]
There is [parking_lot library](https://github.com/Amanieu/parking_lot) that provides custom `Mutex`es and `RwLock`s that are faster than primitives form std.

**Comment by kvark** [comment]
What's the downside of using those? As in - why isn't `std` doing the same thing?

**Comment by torkleyy** [comment]
> why isn't std doing the same thing?

I think they're wrapping the platform-specific ones.

**Comment by kvark** [comment]
I believe this should be blocked before #25 is resolved

**Comment by kvark** [comment]
I don't think this is as relevant now as it was when the issue was filed.

**Comment by kvark** [comment]
Closing in favour of  #44
