### ISSUE TITLE
Questions about differences between Specs/ECS and Froggy/CGS

### ISSUE THREAD

**Issue by jeffparsons** [kvark/froggy#3]
Firstly, thank you, kvark, for all your work on this, and Specs, and every other part of the Rust ecosystem you're involved in!

The approach you're taking with Froggy (and the CGS paradigm more generally) seem eminently sensible to me, so I'm pretty keen to experiment with using it in [PlanetKit](https://github.com/jeffparsons/planetkit) as soon as is practical. But there are a few things I'd like to understand better about the state and direction of the project before I dive in. I'd imagine some of these might be totally undefined at this point, but I'd really appreciate your thoughts either way.

## 1. `World`s and `Planner`s

Do you think you will end up with a `World` type owning component storage like in Specs, or would users of Froggy more likely manage ownership of their `Storage`s themselves?

Possibly related, do you think you will have a `Planner` type to execute systems and manage their priorities, or do you have something else in mind? I notice that you wrote in [your post about the history and state of Specs](https://kvark.github.io/ecs/rust/2017/03/08/specs.html#the-future)...

> [...] It calls us to experiment with future-based task graphs, ad-hoc parallelization, and complex integration with engine/rendering systems [...]

Does this imply that system priority might be defined by building a DAG of `Future`s, where each is equivalent to a `System` in Specs vocabulary, and that the user would then bring their own executor (e.g. from Tokio) to drive those `Future`s to completion?

## 2. Garbage collection

I notice in the [`Pointer` docs](https://docs.rs/froggy/0.1.1/froggy/struct.Pointer.html) you've written that "[t]he pointer holds the storage alive [...]". Is your idea here that if you had a bunch of entities in a game, e.g., lots of NPCs that you don't need to refer to for any other reason, then you'd keep them alive by directly maintaining a collection of `Pointer`s to them somewhere else in your program? Or otherwise in some _other_ component (`froggy::Storage<AllBadGuys>`) that is then referred to at the top level?

This seems to be the obvious reading to me, but given that it changes from the default in Specs of "everything lives forever unless explicitly killed" to "everything dies at some point unless explicitly kept alive", I thought I'd better check to make sure I'm not smoking something. :)

## 3. Mixing Specs with Froggy

I recognise that it's extremely early days for Froggy, so I thought it might be fun to try slowly mixing it in to PlanetKit in a way that minimises churn. I thought the most obvious approach would be to [add my `froggy::Storage` as a resource to my `specs::World`](https://slide-rs.github.io/specs/specs/struct.World.html#method.add_resource) and start by using Froggy via my existing Specs `System`s.

Does that sound crazy to you, or might it be a sensible path for experimentation and eventual migration?

Thanks in advance for any thoughts you might have on these. And please let me know if there's anything I could do to help in figuring out the design / implementation of Froggy.

**Comment by kvark** [comment]
@jeffparsons I missed this issue, messed up my notifications, sorry for late response!
I highly appreciate you taking time to evaluate Froggy and happy to answer your questions/concerns.

> Do you think you will end up with a World type owning component storage like in Specs, or would users of Froggy more likely manage ownership of their Storages themselves?

I hope to have `Storage` things stored manually, with no `World`. Ultimately, it depends on our (parallel) processing story that is yet to unfold.

> Does this imply that system priority might be defined by building a DAG of Futures, where each is equivalent to a System in Specs vocabulary, and that the user would then bring their own executor (e.g. from Tokio) to drive those Futures to completion?

Thing is, we don't have anything for processing yet. I hope to see users defining DAG with futures, conveniently, by hand, but this is future, and it's not clear yet.

> lots of NPCs that you don't need to refer to for any other reason, then you'd keep them alive by directly maintaining a collection of Pointers to them somewhere else in your program? Or otherwise in some other component (froggy::Storage<AllBadGuys>) that is then referred to at the top level?

Yes, the idea is - stuff is alive as long as you point to it. If you don't have a pointer, it may be alive for some time, and you'll be able to iterate it and "revive" it.

> I thought the most obvious approach would be to add my froggy::Storage as a resource to my specs::World and start by using Froggy via my existing Specs Systems.

That does sound absolutely crazy to me. I think it's too early to look into Specs integration, but I appreciate you exploring this direction :)

> And please let me know if there's anything I could do to help in figuring out the design / implementation of Froggy.

Best thing to do now is try to use it for something, be prepared for API changes, and give feedback. Your feedback is already helpful, thank you! 👏 👍

**Comment by jeffparsons** [comment]
Thank you for the clarification and your thoughts on the evolution of Froggy, and no need to apologise! :)

I think what I will do for PlanetKit in the short term is to experiment with using Specs in a more Froggy-like way (using Entity DAGs to emulate CGS), accepting the performance penalty for now, instead of actually using Froggy for it now. I care about performance tomorrow, not today.

Hopefully I'll also find some time to experiment separately from that with different ways to structure systems and their dependencies in Froggy. My initial goals will be:

- Easy to add and remove systems (so need a handle/pointer to them)
- Easy to declare/add dependencies between systems
- Work with external "reactor" / event loop

I don't anticipate that I'll come up with anything generally useful on my pass, but it might be a good starting point for future thought. :grin:

**Comment by kvark** [comment]
You are always welcome to join us at https://gitter.im/almost-ecs/Lobby for further discussion!
We've been making quite some progress here, and looking forward to make Froggy a kick-ass library ;)
