### ISSUE TITLE
Mutable iteration with look-back

### ISSUE THREAD

**Issue by kvark** [kvark/froggy#38]
Current approach is to create a `Pointer` by calling `first()`, that is advanced with `advance`. It's not ergonomic, and neither it is peformant, since we need to lock the `pending` array to get each next epoch.
See also - #19

**Comment by vitvakatu** [comment]
I think I've got an idea, will try today

**Comment by kvark** [comment]
I believe a streaming iterator is still the answer, and I'm nearly done implementing it. I don't think relying on an external library for streaming operations would be useful though.
