### ISSUE TITLE
[RFC] Iterate only live components by default

### ISSUE THREAD

**Issue by kvark** [kvark/froggy#53]
Currently, we have `iter()` for iteration of all stored components and `iter_alive()` for skipping ones with no external references. We also implement `IntoIterator` for `&Storage` that works like `iter()`.

Given that conceptually an unreferenced component ("zombie"?) is as good as dead, I believe our default behavior should strictly be working with alive components only (for both `iter()` and `IntoIterator`). Iterating zombies as well should be opt-in, only for optimization purposes when the user doesn't care.

**Comment by vitvakatu** [comment]
Do we even need to iterate over dead components?

**Comment by kvark** [comment]
@vitvakatu I think some use cases will not care if an item is not referenced, and for those it might be an optimization to avoid checking the `meta`.
