### ISSUE TITLE
Fate of Cube-ception Demo

### ISSUE THREAD

**Issue by kvark** [kvark/froggy#57]
I feel that the demo carries a bit too much logic that is irrelevant to Froggy. It's basically replicating a part of three-rs with bare minimum of scene graph and materials. It has been ported as an example here - https://github.com/kvark/three-rs/pull/36

I think we should remove it from this repo, therefore. Does anyone finds the value in it? We can keep it, if it's helpful.

**Comment by vitvakatu** [comment]
I don't mind. This demo shows some basic methods of work with froggy, but it's too complex and contains low-level code of gfx, that makes it difficult to see parts relevant to froggy.

**Comment by DaseinPhaos** [comment]
Any substitute if this demo got removed?

**Comment by kvark** [comment]
There doesn't have to be a demo. When Froggy was just born, I needed an app to show it in action. Now there is Three-rs.

**Comment by kvark** [comment]
I figured we can remove it only when Three-rs auto-instancing is implemented to provide equivalent performance.

**Comment by OliverUv** [comment]
I'm interested in using Froggy (but, for now, not three-rs) and I would much prefer reading the 1k line demo file to scouring a big framework for its Froggy usages.

**Comment by vitvakatu** [comment]
I'm going to rewrite the demo using wgpu (just to check it and learn it myself), but I don't want to include the updated version to this repo. Maybe a simple link to another repo will suffice.

**Comment by kvark** [comment]
Sounds like a great idea!

**Comment by wyhinton** [comment]
I found the demo very useful, I wish more libraries included non-trivial demos like Cube-ception.

**Comment by kvark** [comment]
Good news! Cube-ception demo as found a new home as a Baryon example - https://github.com/kvark/baryon#readme
