### ISSUE TITLE
Implement PartialOrd for pointers

### ISSUE THREAD

**Issue by kvark** [kvark/froggy#61]
This would allow predicting the results of cursor lookahead/back by comparing two pointers. Comparison is only meaningful if they point to the same storage, otherwise return `None`.

**Comment by vitvakatu** [comment]
What result should be for comparing two pointers from different storages?

**Comment by kvark** [comment]
@vitvakatu that's the point of `PartialOrd`, to provide a way to compare stuff that *sometimes* is comparable: https://doc.rust-lang.org/stable/std/cmp/trait.PartialOrd.html#tymethod.partial_cmp

Notice the result type. For different storages, return `None`.
