### ISSUE TITLE
request textured example with pyramid, light source and camera move-rotation-zoom

### ISSUE THREAD

**Issue by laticoda** [kvark/froggy#74]
Hi, could you provide this
an example with pyramidal geometry , or spheric Bubbles, with different textures depending the face,
source light withj shadow, and camera move+rotation+zoom.
;-)

**Comment by kvark** [comment]
Graphics features are not the focus of this library. I don't think such an example is needed here. But maybe elsewhere, e.g. in glium/luminance?
